USE [master]
GO
/****** Object:  Database [seminarskirad]    Script Date: 4/16/2023 7:22:22 PM ******/
CREATE DATABASE [seminarskirad]

GO
ALTER DATABASE [seminarskirad] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [seminarskirad].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [seminarskirad] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [seminarskirad] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [seminarskirad] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [seminarskirad] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [seminarskirad] SET ARITHABORT OFF 
GO
ALTER DATABASE [seminarskirad] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [seminarskirad] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [seminarskirad] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [seminarskirad] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [seminarskirad] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [seminarskirad] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [seminarskirad] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [seminarskirad] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [seminarskirad] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [seminarskirad] SET  DISABLE_BROKER 
GO
ALTER DATABASE [seminarskirad] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [seminarskirad] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [seminarskirad] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [seminarskirad] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [seminarskirad] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [seminarskirad] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [seminarskirad] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [seminarskirad] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [seminarskirad] SET  MULTI_USER 
GO
ALTER DATABASE [seminarskirad] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [seminarskirad] SET DB_CHAINING OFF 
GO
ALTER DATABASE [seminarskirad] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [seminarskirad] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [seminarskirad] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [seminarskirad] SET QUERY_STORE = OFF
GO
USE [seminarskirad]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [seminarskirad]
GO
/****** Object:  Table [dbo].[Grupa]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grupa](
	[GrupaID] [int] IDENTITY(1,1) NOT NULL,
	[NazivGrupe] [nvarchar](255) NOT NULL,
	[Uzrast] [int] NOT NULL,
	[ProgramID] [int] NOT NULL,
	[Vaspita?ID] [int] NOT NULL,
 CONSTRAINT [PK_Grupa] PRIMARY KEY CLUSTERED 
(
	[GrupaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ogranicenjagrupa] UNIQUE NONCLUSTERED 
(
	[NazivGrupe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Korisnik]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Korisnik](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](50) NOT NULL,
	[Prezime] [nvarchar](50) NOT NULL,
	[KorisnickoIme] [nvarchar](50) NOT NULL,
	[Lozinka] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pohadjanje]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pohadjanje](
	[U?enikID] [int] NOT NULL,
	[GrupaID] [int] NOT NULL,
	[DatumOD] [datetime] NOT NULL,
	[DatumDO] [datetime] NOT NULL,
 CONSTRAINT [PK_Pohadjanje] PRIMARY KEY CLUSTERED 
(
	[U?enikID] ASC,
	[GrupaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Program]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Program](
	[ProgramID] [int] IDENTITY(1,1) NOT NULL,
	[Naziv] [nchar](40) NOT NULL,
	[Opis] [nchar](400) NOT NULL,
 CONSTRAINT [PK_Program] PRIMARY KEY CLUSTERED 
(
	[ProgramID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ogranicenja???????] UNIQUE NONCLUSTERED 
(
	[Naziv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Table]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table](
	[Id] [int] NOT NULL,
	[Naziv] [nchar](10) NOT NULL,
	[Espb] [nchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[U?enik]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[U?enik](
	[U?enikID] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](255) NOT NULL,
	[Prezime] [nvarchar](255) NOT NULL,
	[DatumRodjenja] [datetime] NOT NULL,
	[Pol] [nvarchar](255) NOT NULL,
	[KontaktRoditelja] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_U?enik] PRIMARY KEY CLUSTERED 
(
	[U?enikID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ogranicenjaucenik] UNIQUE NONCLUSTERED 
(
	[Ime] ASC,
	[Prezime] ASC,
	[DatumRodjenja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vaspita?]    Script Date: 4/16/2023 7:22:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vaspita?](
	[Vaspita?ID] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](255) NOT NULL,
	[Prezime] [nvarchar](255) NOT NULL,
	[Pol] [nvarchar](255) NOT NULL,
	[Kontakt] [nvarchar](255) NOT NULL,
	[ProgramID] [int] NOT NULL,
 CONSTRAINT [PK_Vaspita?] PRIMARY KEY CLUSTERED 
(
	[Vaspita?ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ogranicenjavaspitac] UNIQUE NONCLUSTERED 
(
	[Ime] ASC,
	[Prezime] ASC,
	[Kontakt] ASC,
	[ProgramID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Grupa]  WITH CHECK ADD  CONSTRAINT [FK_Grupa_Program] FOREIGN KEY([ProgramID])
REFERENCES [dbo].[Program] ([ProgramID])
GO
ALTER TABLE [dbo].[Grupa] CHECK CONSTRAINT [FK_Grupa_Program]
GO
ALTER TABLE [dbo].[Grupa]  WITH CHECK ADD  CONSTRAINT [FK_Grupa_Vaspita?] FOREIGN KEY([Vaspita?ID])
REFERENCES [dbo].[Vaspita?] ([Vaspita?ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Grupa] CHECK CONSTRAINT [FK_Grupa_Vaspita?]
GO
ALTER TABLE [dbo].[Pohadjanje]  WITH CHECK ADD  CONSTRAINT [FK_Pohadjanje_Grupa] FOREIGN KEY([GrupaID])
REFERENCES [dbo].[Grupa] ([GrupaID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Pohadjanje] CHECK CONSTRAINT [FK_Pohadjanje_Grupa]
GO
ALTER TABLE [dbo].[Pohadjanje]  WITH CHECK ADD  CONSTRAINT [FK_Pohadjanje_U?enik] FOREIGN KEY([U?enikID])
REFERENCES [dbo].[U?enik] ([U?enikID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Pohadjanje] CHECK CONSTRAINT [FK_Pohadjanje_U?enik]
GO
ALTER TABLE [dbo].[Vaspita?]  WITH CHECK ADD  CONSTRAINT [FK_Vaspita?_Program] FOREIGN KEY([ProgramID])
REFERENCES [dbo].[Program] ([ProgramID])
GO
ALTER TABLE [dbo].[Vaspita?] CHECK CONSTRAINT [FK_Vaspita?_Program]
GO
USE [master]
GO
ALTER DATABASE [seminarskirad] SET  READ_WRITE 
GO
